### health check: ready
GET 127.0.0.1:8558/mycluster/health/ready

### health check: alive
GET 127.0.0.1:8558/mycluster/health/alive

###
GET 127.0.0.1:8559/mycluster/health/ready

###
GET 127.0.0.1:8559/mycluster/health/alive

###
GET 127.0.0.1:8560/mycluster/health/ready

###
GET 127.0.0.1:8560/mycluster/health/alive
