kind: Deployment
apiVersion: apps/v1
metadata:
  name: akka-sample-v1
  namespace: dev
  labels:
    app: akka-sample
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: akka-sample
      version: v1
  template:
    metadata:
      labels:
        app: akka-sample
        version: v1
    spec:
      containers:
        - name: akka-sample
          image: registry.cn-hangzhou.aliyuncs.com/assad-pub/akka-k8s-sample
          readinessProbe:
            httpGet:
              path: "/ready"
              port: http-management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: http-management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: http-web
              containerPort: 8080
              protocol: TCP
            - name: http-management
              containerPort: 8558
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent

---
kind: Service
apiVersion: v1
metadata:
  name: akka-sample
  namespace: dev
  labels:
    app: akka-sample
    version: v1
spec:
  ports:
    - name: http-web
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http-manage
      protocol: TCP
      port: 8558
      targetPort: 8558
  selector:
    app: akka-sample
  type: ClusterIP
  sessionAffinity: None

